// Isometric camera/rendering and projected controls. Existing suites also exercise Classic.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1]);
const hooks=`window.gameTest={get viewZoom(){return viewZoom},begin,applyProfile,saveProfile,selectSlot,update,draw,spawnEnemy,spawnBoss,wallAt,segmentBlocked,moveAroundWalls,floorEntry,renderMenu,renderSettings,useDash,useUltimate,inputVector,projectVector,visiblePoint,cameraFocusY,refreshCameraBounds,saveRun,readRun,restoreRun,makeSaveCode,loadSaveCode,raiseMinion,updateRpgPresentation,
get hero(){return hero},get art(){return art},get worldW(){return worldW},get worldH(){return worldH},get profile(){return profile},get slots(){return slots},get joy(){return joy},get enemies(){return enemies},set enemies(v){enemies=v},get companions(){return companions},get mode(){return mode},set mode(v){mode=v},get clock(){return clock},get dungeon(){return dungeon},get effects(){return rpgFx},get ghosts(){return dashGhosts},get rpgPreview(){return rpgPreview},set selectedHero(v){selectedHero=v},set selectedMode(v){selectedMode=v},set spawn(v){spawn=v}};`;
function instrument(live=false){let s=source;if(!live)s=s.replaceAll('requestAnimationFrame(frame);','').replace('function sfx(kind) {','function sfx(kind) { return;');return s.replace('function flushScene(){queueScene=false;sceneQueue.sort((a,b)=>a.depth-b.depth);','function flushScene(){queueScene=false;sceneQueue.sort((a,b)=>a.depth-b.depth);window.sortedDepths=sceneQueue.map(i=>i.depth);').replace('      })();',hooks+'\n      })();');}
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/'||name==='/live'){res.setHeader('Content-Type','text/html');return res.end(instrument(name==='/live'));}const file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.end(fs.readFileSync(file));});
const heroes=['gravecaller','ranger','ember','bloodknight','sunwarden'],sizes=[{width:390,height:844},{width:844,height:390}],errors=[],report={scenes:[],mechanics:null,native:[],browserErrors:errors};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const url=`http://localhost:${server.address().port}`;
try{const page=await browser.newPage({viewport:sizes[1],hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'RPG Preview',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');});await page.goto(url);await page.evaluate(()=>gameTest.selectSlot(0));await page.waitForFunction(()=>gameTest.art['bloodknight-cast']&&gameTest.art['ranger-cast']&&gameTest.art['sunwarden-cast']&&gameTest.art['prop-brazier']);
for(const size of sizes){await page.setViewportSize(size);for(const kind of heroes){for(let floor=1;floor<=5;floor++){const result=await page.evaluate(({kind,floor,size})=>{const g=gameTest;function check(v,m){if(!v)throw Error(kind+'/'+floor+': '+m);}g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();g.floorEntry(floor);g.dungeon.title=0;g.spawn=999;g.enemies=[];g.draw();check(g.rpgPreview,'Isometric not default');check(g.worldW>=size.width||g.worldH>=size.height,'Invalid inverse frustum');check(window.sortedDepths.length>0&&window.sortedDepths.every((v,i,a)=>i===0||v>=a[i-1]),'Actors/walls not depth sorted');
const project=g.projectVector,input=g.inputVector;for(const [x,y]of [[1,0],[0,1],[-1,0],[0,-1],[.4,.7]]){const v=input(x,y),p=project(v.x,v.y);check(Math.abs(x-p.x)<1e-9&&Math.abs(y-p.y)<1e-9,'Projection inverse');}
const start={x:g.hero.x,y:g.hero.y};g.joy.dx=1;g.joy.dy=0;g.update(.025);g.joy.dx=g.joy.dy=0;const moved=project(g.hero.x-start.x,g.hero.y-start.y);check(moved.x>0&&Math.abs(moved.y)<.001,'Right input does not move screen-right');check(!g.wallAt(g.hero.x,g.hero.y,g.hero.r),'Movement inside wall');
const beforeDash={x:g.hero.x,y:g.hero.y};g.joy.dx=0;g.joy.dy=-1;check(g.useDash(),'Projected Dash');for(let i=0;i<10;i++)g.update(.025);g.joy.dx=g.joy.dy=0;const dash=project(g.hero.x-beforeDash.x,g.hero.y-beforeDash.y);check(dash.y<0&&Math.abs(dash.x)<.01,'Dash direction not screen-up');check(!g.wallAt(g.hero.x,g.hero.y,g.hero.r),'Dash into wall');
// Navigation still uses the authored world map. Convert a short world route back to screen joystick coordinates.
let travel=0;for(let step=0;step<80;step++){const desired=project(1,0),length=Math.hypot(desired.x,desired.y);g.joy.dx=desired.x/length;g.joy.dy=desired.y/length;const old=g.hero.x;g.update(.025);travel+=Math.max(0,g.hero.x-old);}g.joy.dx=g.joy.dy=0;check(travel>20&&!g.wallAt(g.hero.x,g.hero.y,g.hero.r),'World route/projected joystick');
// New ordinary arrivals must be outside the projected viewport, not merely outside raw world axes.
g.enemies=[];for(let i=0;i<10;i++){const enemy=g.spawnEnemy('ghoul');if(enemy)check(!g.visiblePoint(enemy.x,enemy.y,65),'Enemy spawned on-screen');}
g.hero.ultimateCharge=100;g.useUltimate();check(g.effects.some(f=>f.kind===kind),'Missing hero Ultimate presentation');g.updateRpgPresentation(.1);g.draw();const dashRect=document.querySelector('#dashButton').getBoundingClientRect(),hud=document.querySelector('.hud').getBoundingClientRect(),map=document.querySelector('#dungeonMap').getBoundingClientRect();check(dashRect.y>=hud.bottom,'Skill/HUD overlap');check(map.x>size.width/2&&map.bottom<=size.height,'Projected minimap placement');return {hero:kind,floor,...size,sceneItems:window.sortedDepths.length,worldViewport:[+g.worldW.toFixed(2),+g.worldH.toFixed(2)],movement:'screen-aligned',spawns:'offscreen',ultimate:'animated'};},{kind,floor,size});report.scenes.push(result);
if(floor===1)await page.screenshot({path:`/tmp/action-rpg-${kind}-${size.width}.png`});}
}console.log('PASS: all 25 hero/floor scenes, projected input/dash/walls/spawns/Ultimates',size);}
report.mechanics=await page.evaluate(()=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}g.selectedHero='bloodknight';g.selectedMode='descent';g.begin();g.dungeon.title=0;g.enemies=[];g.spawn=999;g.hero.inv=0;g.spawnBoss('colossus');const boss=g.enemies.find(e=>e.type==='boss');boss.x=480;boss.y=800;boss.speed=0;boss.pulse=999;boss.slamClock=999;boss.slam={x:g.hero.x,y:g.hero.y,r:1000,damage:37,time:.05,duration:1.3};const hp=g.hero.hp,armor=g.hero.armor;g.useDash();g.update(.025);g.update(.025);check(g.hero.hp===hp&&g.hero.armor===armor&&!boss.slam,'Projected Dash/slam invulnerability');g.hero.ultimateCharge=100;g.useUltimate();const life=g.effects[0]?.life;check(life>0,'No effect to pause');g.mode='paused';g.update(1);check(g.effects[0]?.life===life,'Paused presentation ages');g.mode='play';g.hero.ultimateCharge=61;g.saveRun(true);const code=g.makeSaveCode();check(g.loadSaveCode(code).profile.version===2&&g.readRun().version===11,'Versions changed');check(!g.readRun().rpgFx&&!g.readRun().dashGhosts,'Transient visuals serialized');g.restoreRun();check(g.dungeon.floor===1&&g.dungeon.elapsed===0&&!g.effects.length&&!g.ghosts.length,'Floor checkpoint visual reset');
g.selectedHero='gravecaller';g.selectedMode='endless';g.begin();g.hero.ultimateCharge=72;g.saveRun(true);g.restoreRun();check(g.hero.ultimateCharge===72,'Endless charge lost');g.renderMenu('settings');const button=[...document.querySelectorAll('#menuPage button')].find(b=>b.textContent.startsWith('GRAPHICS'));check(button&&button.textContent.includes('ISOMETRIC'),'Graphics comparison option');button.click();check(!g.rpgPreview&&Math.abs(g.worldW-document.querySelector('#view').clientWidth/g.viewZoom)<0.5,'Classic fallback');return 'projected Dash versus actual slams, paused cosmetic timers, unchanged v2/v11/EC1 saves, transient visual reset, Endless state, Settings Classic fallback';});console.log('PASS:',report.mechanics);
// Real frame loop and touch/keyboard buttons. Timings are render diagnostics, not a phone FPS claim.
for(const size of sizes)for(const kind of heroes){const live=await browser.newPage({viewport:size,hasTouch:true,deviceScaleFactor:3});live.on('pageerror',e=>errors.push(e.message));await live.addInitScript(kind=>{localStorage.setItem('ember-crypt-rpg-preview','1');localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Live RPG',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');localStorage.setItem('ember-crypt-slot-1-profile',JSON.stringify({version:2,selectedHero:kind,ranger:true,ember:true,bloodknight:true,sunwarden:true,migrated:true,upgrades:{},embers:0,total:0}));},kind);await live.goto(url+'/live');await live.getByRole('button',{name:'TAP TO START'}).click({force:true});await live.getByRole('button',{name:'PLAY',exact:true}).click();await live.getByRole('button',{name:/^THE DESCENT/}).click();await live.getByRole('button',{name:/^ENTER THE CRYPT/}).click();await live.waitForTimeout(2800);await live.keyboard.down('d');await live.locator('#dashButton').tap();await live.waitForTimeout(400);await live.keyboard.up('d');await live.evaluate(()=>{gameTest.hero.ultimateCharge=100;});await live.locator('#ultimateButton').tap();await live.waitForTimeout(200);assert(await live.evaluate(()=>gameTest.mode==='play'&&gameTest.hero.ultimateCharge<100&&gameTest.rpgPreview));await live.screenshot({path:`/tmp/action-rpg-live-${kind}-${size.width}.png`});const timings=await live.evaluate(()=>{const t=[];for(let i=0;i<30;i++){const a=performance.now();gameTest.draw();t.push(performance.now()-a);}t.sort((a,b)=>a-b);return {medianMs:+t[15].toFixed(2),maxMs:+t[29].toFixed(2)};});report.native.push({hero:kind,...size,...timings});await live.close();}
const high=await browser.newPage({viewport:{width:1440,height:3200},deviceScaleFactor:3});await high.goto(url);const pixels=await high.locator('#view').evaluate(c=>c.width*c.height);assert(pixels<=1800000,'High-resolution pixel budget exceeded');await high.close();report.pixelBudget={deviceScaleFactor:3,cssWidth:1440,cssHeight:3200,pixels};
assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(root,'tests/action-rpg-results.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS: native loop, both orientations/all five heroes, render timings and no browser errors');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
