// Presentation regressions: deleting a recoil profile, moving physics instead of
// the sprite, dropping the quality cap, or leaking feedback into saves must fail.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),http=require('node:http');
const root=path.resolve(__dirname,'..'),file=path.join(root,'assets/cinematic/combat-feel.js');
assert(fs.existsSync(file),'Combat Feel presentation module is missing');
const window={},math=Object.create(Math);math.random=()=>{throw Error('Presentation consumed gameplay RNG')};
vm.runInNewContext(fs.readFileSync(file,'utf8'),{window,Math:math});
const feel=window.EmberCombatFeel,heroes=['gravecaller','bloodknight','ranger','sunwarden','ember','rogue','frostwarden'];
const signatures=new Set();
for(const kind of heroes){
 const cast=kind==='bloodknight'?.24:kind==='frostwarden'?.28:.18;
 const idle=feel.pose({kind,cast:0,direction:{x:1,y:0}});
 assert.equal(idle.x,0);assert.equal(idle.rotation,0);assert.equal(idle.scaleX,1);
 const frames=Array.from({length:9},(_,i)=>feel.pose({kind,cast:cast*(1-i/9),direction:{x:1,y:0}}));
 assert(frames.some(f=>Math.abs(f.x)+Math.abs(f.y)+Math.abs(f.rotation)>.01),kind+' has no attack motion');
 for(const f of frames){assert(Math.abs(f.x)<=7&&Math.abs(f.y)<=5&&Math.abs(f.rotation)<=.12);assert(f.scaleX>=.9&&f.scaleX<=1.12);}
 const left=feel.pose({kind,cast:cast*.6,direction:{x:-1,y:0}}),right=feel.pose({kind,cast:cast*.6,direction:{x:1,y:0}});
 assert(Math.abs(left.x+right.x)<1e-8,kind+' recoil does not mirror');
 signatures.add(JSON.stringify(frames));
}
assert.equal(signatures.size,7,'Heroes share identical attack motion');
const enemy={x:100,y:100,hp:50},before=JSON.stringify(enemy),q={maxAtmosphere:32};
feel.hit(enemy,{x:1,y:0,color:'#fff',crit:true,clock:1},q);
assert.equal(JSON.stringify(enemy),before,'Hit feedback wrote to enemy physics/save state');
const r=feel.reaction(enemy,1.04,(x,y)=>({x,y}));assert(r.x>0&&Math.abs(r.x)<=5);
assert.deepEqual(JSON.parse(JSON.stringify(feel.reaction(enemy,1.04,(x,y)=>({x,y})))),JSON.parse(JSON.stringify(r)),'Frozen game clock advances recoil');
assert.equal(feel.reaction(enemy,2,(x,y)=>({x,y})).x,0,'Recoil outlasted its cosmetic lifetime');
for(const atmosphere of [32,16,8]){
 feel.reset();for(let i=0;i<200;i++)feel.hit({}, {x:0,y:-1,color:'#fff',crit:i%2===0,clock:1},{maxAtmosphere:atmosphere});
 assert(feel.stats().queued<=(atmosphere===32?24:atmosphere===16?16:8));
}
feel.reset();feel.hit(enemy,{x:1,y:0,color:'#fff',crit:true,clock:1},q);
const depths=[];feel.draw({}, {clock:1.05,isometric:true,quality:q,visiblePoint:()=>true,sceneItem:(x,y)=>depths.push(x+y),projectVector:(x,y)=>({x,y})});
assert(depths[0]>enemy.x+enemy.y,'Impact paints behind the struck enemy');
feel.reset();assert.equal(feel.stats().queued,0);
console.log('PASS cosmetic motion: seven distinct mirrored profiles, bounded offsets, RNG isolation, transient reactions and quality caps');
const {chromium}=require('playwright'),raw=fs.readFileSync(path.join(root,'index.html'),'utf8');
const hooks=`window.feelTest={begin,fx,updateAdventure,equipAdventureLegend,draw,update,selectSlot,applyProfile,damageEnemy,spawnEnemy,spawnBoss,saveRun,readRun,makeSaveCode,loadSaveCode,useDash,useUltimate,projectVector,inputVector,pauseRun,resumePaused,get hero(){return hero},get enemies(){return enemies},set enemies(v){enemies=v},get dungeon(){return dungeon},get quality(){return visualQuality},get clock(){return clock},set clock(v){clock=v},get mode(){return mode},set mode(v){mode=v},set spawn(v){spawn=v},set attack(v){attack=v},set selectedHero(v){selectedHero=v},set selectedMode(v){selectedMode=v}};`;
const source=raw.replace('function sfx(kind) {','function sfx(kind) { return;').replace('function music(kind) {','function music(kind) { return;').replaceAll('requestAnimationFrame(frame);','').replace('      })();',hooks+'\n      })();');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;if(name==='/'||name==='/native'){res.setHeader('Content-Type','text/html');return res.end(name==='/'?source:raw.replace('      })();',hooks+'\n      })();'))}const f=path.resolve(root,'.'+name);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end()}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':'application/octet-stream');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});const report={scenes:[],errors:[],audio:null};const out=process.env.ARTIFACT_DIR||'/tmp/combat-feel-artifacts';fs.mkdirSync(out,{recursive:true});try{
 const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,deviceScaleFactor:3});p.on('pageerror',e=>report.errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Combat Feel',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');localStorage.setItem('ember-crypt-muted','1')});const url='http://127.0.0.1:'+server.address().port;await p.goto(url);await p.waitForFunction(()=>window.feelTest&&EmberHeroAnimation.diagnostics().frames===210);
 for(const size of [{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(size);for(const hero of heroes){const result=await p.evaluate(({hero})=>{const g=feelTest;g.selectSlot(0);g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true,rogue:true,frostwarden:true});g.selectedHero=hero;g.selectedMode='descent';g.begin();g.dungeon.title=0;g.spawn=999;g.enemies=[];g.draw();g.hero.cast=(hero==='bloodknight'?.24:hero==='frostwarden'?.28:.18)*.6;g.hero.faceX=1;g.hero.faceY=0;g.draw();g.spawnEnemy('skeleton');const e=g.enemies.at(-1);e.x=g.hero.x+42;e.y=g.hero.y;e.hp=e.max=1000;const old={x:e.x,y:e.y,vx:e.vx,vy:e.vy};g.damageEnemy(e,10,hero==='rogue'?'poison':hero==='bloodknight'?'blood':'neutral',0,true,hero!=='rogue');g.clock+=.055;const afterDamage=JSON.stringify(g.hero),enemyState=JSON.stringify(e);g.draw();if(JSON.stringify(g.hero)!==afterDamage||JSON.stringify(e)!==enemyState)throw Error('Rendering changed simulation');if(e.x!==old.x||e.y!==old.y)throw Error('Feedback moved enemy physics');if(!EmberCombatFeel.stats().queued)throw Error('Hit hook absent');const rng=Math.random;Math.random=()=>{throw Error('Cosmetic RNG leaked')};EmberCombatFeel.pose({kind:hero,cast:.1,direction:{x:1,y:0}});Math.random=rng;g.saveRun();const saved=g.readRun();if(!saved||saved.version!==12)throw Error('Run version changed');if(/hitReaction|combatFeel|recoilAt/.test(JSON.stringify(saved)))throw Error('Cosmetics leaked into save');g.spawnBoss('warden');g.draw();if(!EmberHeroAnimation.diagnostics().lastDraw[hero])throw Error('Authored art missing');return {hero,queued:EmberCombatFeel.stats().queued,pixels:document.querySelector('canvas').width*document.querySelector('canvas').height,runVersion:saved.version,physicsPreserved:true};},{hero});assert(result.pixels<=1800000);report.scenes.push({...size,...result});await p.screenshot({path:path.join(out,hero+'-'+size.width+'.png')});}}
 // Legendary fire-patch ticks must not masquerade as direct fire strikes.
 report.periodic=await p.evaluate(()=>{const g=feelTest;g.selectedHero='ember';g.begin();g.dungeon.title=0;g.enemies=[];g.spawn=999;g.draw();g.spawnEnemy('skeleton');const e=g.enemies.at(-1);e.x=g.hero.x+40;e.y=g.hero.y;e.hp=e.max=10000;g.equipAdventureLegend();g.hero.adventure.procAt=g.clock-1;g.damageEnemy(e,10,'fire',0,true);EmberCombatFeel.reset();const before=e.hp;g.updateAdventure(.41);if(!(e.hp<before))throw Error('Legendary patch stopped dealing damage');if(EmberCombatFeel.stats().queued)throw Error('Periodic fire patch emitted direct-hit feedback');g.damageEnemy(e,5,'poison');if(!EmberCombatFeel.stats().queued)throw Error('Secondary direct poison strike lost feedback');return {patchDamage:before-e.hp,periodicSuppressed:true,secondaryPoison:true};});
 // Actual decoded sampled audio: attacks and hero-specific impacts must share the 12-voice limiter.
 report.audio=await p.evaluate(async()=>{const c=new AudioContext();await c.resume();await EmberAudio.ensure(c);const kinds=['gravecaller','bloodknight','ranger','sunwarden','ember','rogue','frostwarden'];for(const h of kinds){if(!EmberAudio.ready('impact',c,h))throw Error('Missing '+h+' impact');if(!EmberAudio.ready('shoot',c,h))throw Error('Missing '+h+' attack');EmberAudio.play('shoot',c,h);EmberAudio.play('impact',c,h);EmberAudio.play('crit',c,h);}EmberAudio.stop(c);const scheduled=EmberAudio.stats(c).scheduled;const first=EmberAudio.play('hit',c,'ember'),second=EmberAudio.play('impact',c,'ember');if(!first||second)throw Error('Duplicated hit/impact layers');const s={...EmberAudio.stats(c),coalesced:!second,impactVoices:EmberAudio.stats(c).scheduled-scheduled};EmberAudio.stop(c);const stopped=EmberAudio.stats(c).active;await c.close();return {...s,stopped}});assert(report.audio.maximum<=12);assert.equal(report.audio.stopped,0);assert(report.audio.decoded>=29);
 // Classic uses immediate canvas painting, not the isometric depth queue.
 const classic=await p.evaluate(()=>{EmberCombatFeel.reset();EmberCombatFeel.hit({x:40,y:40},{x:1,y:0,color:'#fff',clock:1},{maxAtmosphere:8});const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');let strokes=0;const stroke=ctx.stroke.bind(ctx);ctx.stroke=()=>{strokes++;stroke();};EmberCombatFeel.draw(ctx,{clock:1.05,isometric:false,quality:{maxAtmosphere:8},visiblePoint:()=>true,projectVector:(x,y)=>({x,y}),sceneItem:()=>{throw Error('Classic feedback entered the isometric depth queue')},billboard:(x,y,paint)=>{ctx.save();ctx.translate(x,y);paint();ctx.restore();}});return {strokes,particles:EmberCombatFeel.stats().particles};});assert(classic.strokes>0);assert(classic.particles<=16);report.classic=classic;
 // Cosmetic modules may fail offline; the existing sprite/attack path must still render.
 const fallback=await p.evaluate(()=>{const module=window.EmberCombatFeel,g=feelTest,before=JSON.stringify(g.hero);window.EmberCombatFeel=undefined;g.draw();window.EmberCombatFeel=module;return before===JSON.stringify(g.hero)});assert(fallback,'Optional module failure changed simulation');
 // Real RAF and desktop keyboard: no manual-attack button, frozen pause clock,
 // and no feedback-induced input lag or invulnerability/Ultimate changes.
 const live=await b.newPage({viewport:{width:844,height:390},hasTouch:true});live.on('pageerror',e=>report.errors.push(e.message));await live.addInitScript(()=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Live',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');localStorage.setItem('ember-crypt-muted','1')});await live.goto(url+'/native');await live.waitForFunction(()=>window.feelTest&&EmberHeroAnimation.diagnostics().frames===210);
 report.controls=[];
 for(const hero of heroes){await live.evaluate(hero=>{const g=feelTest;g.selectSlot(0);g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true,rogue:true,frostwarden:true});g.selectedHero=hero;g.selectedMode='descent';g.begin();g.dungeon.title=0;g.spawn=999;g.enemies=[];g.hero.ultimateCharge=100;g.spawnEnemy('skeleton');const e=g.enemies.at(-1);e.x=g.hero.x+45;e.y=g.hero.y;e.hp=e.max=10000;},hero);const before=await live.evaluate(()=>({x:feelTest.hero.x,y:feelTest.hero.y,clock:feelTest.clock}));await live.keyboard.down('d');await live.waitForTimeout(160);await live.keyboard.press('Space');await live.keyboard.up('d');const dash=await live.evaluate(()=>({cd:feelTest.hero.dashCd,inv:feelTest.hero.inv}));assert(dash.cd>0&&dash.inv>0,'Keyboard dash failed for '+hero);await live.keyboard.press('e');await live.waitForTimeout(100);const result=await live.evaluate(before=>{const g=feelTest;return {moved:Math.hypot(g.hero.x-before.x,g.hero.y-before.y)>1,advanced:g.clock>before.clock,ultimate:g.hero.ultimateCharge<100,onlySkills:!document.querySelector('#attackButton'),feedback:EmberCombatFeel.stats()};},before);assert(result.moved&&result.advanced&&result.ultimate&&result.onlySkills,'Live controls failed '+hero);const freeze=await live.evaluate(()=>{feelTest.pauseRun();return feelTest.clock});await live.waitForTimeout(100);assert.equal(await live.evaluate(()=>feelTest.clock),freeze,'Paused feedback advanced simulation');await live.evaluate(()=>feelTest.resumePaused());report.controls.push({hero,...result});}
 await live.close();
 assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,'combat-feel-results.json'),JSON.stringify(report,null,2));console.log('PASS real browser: all seven heroes in portrait/landscape, draw/physics/save isolation, boss readability, real sampled audio voice cap; screenshots:',out);
 }finally{await b.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exit(1)});
