// Normal-stat Floor 1 survival diagnostics in Chromium. No HP/damage/shrine buffs.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const baselineCommit=process.env.BASELINE_COMMIT||'d11e59a6c2cd72dfc3fefbb3052fdce61fb29cf1';
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),before=execFileSync('git',['show',baselineCommit+':index.html'],{cwd:root,encoding:'utf8'});
for(const m of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1]);
const hooks=`window.gameTest={begin,applyProfile,update,draw,swingBlade,spawnEnemy,floorEntry,updateZoneHazards,
get hero(){return hero},get enemies(){return enemies},set enemies(v){enemies=v},get joy(){return joy},get clock(){return clock},get mode(){return mode},get level(){return level},get kills(){return kills},get dungeon(){return dungeon},get zoneHazards(){return zoneHazards},get spawn(){return spawn},get profile(){return profile},get attack(){return attack},set selectedHero(v){selectedHero=v},set selectedMode(v){selectedMode=v},wallAt};`;
function instrument(s){return s.replace('function sfx(kind) {','function sfx(kind) { return;').replaceAll('requestAnimationFrame(frame);','').replace('      })();',hooks+'\n      })();');}
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/'||name==='/before'){res.setHeader('Content-Type','text/html');return res.end(instrument(name==='/before'?before:source));}const file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.clear());const results=[];
for(const version of (process.env.CURRENT_ONLY?['after']:['before','after'])){await page.goto(`http://localhost:${server.address().port}/${version==='before'?'before':''}`);await page.getByRole('button',{name:'TAP TO START'}).click({force:true});await page.getByRole('button',{name:'SLOT 1 · + NEW CHARACTER',exact:true}).click();await page.locator('input').fill('Normal');await page.getByRole('button',{name:'CREATE & PLAY',exact:true}).click();
for(const kind of (process.env.HERO_FILTER?process.env.HERO_FILTER.split(','):version==='before'?['mage','storm','ember','bloodknight']:['gravecaller','ranger','ember','bloodknight','sunwarden']))for(const seed of [17,37,71,113,151]){
const result=await page.evaluate(({kind,seed,version})=>{let state=seed;Math.random=()=>{state=(state+0x6D2B79F5)|0;let t=Math.imul(state^(state>>>15),1|state);t=(t+Math.imul(t^(t>>>7),61|t))^t;return ((t^(t>>>14))>>>0)/4294967296;};const g=gameTest;
g.applyProfile({bosses:3,storm:true,ember:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();const initial={hp:g.hero.hp,armor:g.hero.armor,damage:g.hero.damage,depth:g.hero.depth,shrine:{...g.profile.upgrades}};
const priorities=kind==='bloodknight'?['EVOLUTION','Crimson Thirst','Bloodletting','Stone Skin','Blood Fairy','Shockwave','Earth Spikes','Berserk','Twin Flame','Long Reach','Quake Step','Earth Fairy','Quick Hands','Iron Heart']:['EVOLUTION','Twin Flame','Quick Hands','Bone Armor','Raise Legion','Siphon','Spirit Wisps','Ice Trap','Glacier Wolf','Frost Arrows','Chain Shot','Radiance','Sanctuary','Gale','Cyclone','ARCANE LANCE','Chain Spark','METEOR SIGIL','GRAVE NOVA','Firebrand','Venom Bolts','Fairy','Iron Heart'];let maxImps=0,maxLava=0,decisions=0;
for(let step=0;step<40*180+200;step++){
 if(g.mode==='over'||g.mode==='error'||g.mode==='victory'||g.clock>=180||g.dungeon.floor!==1)break;
 if(g.mode!=='play'){let buttons=[...document.querySelectorAll('#choices .choice')].filter(b=>!b.disabled);if(!buttons.length)throw Error('No offered choice: '+g.mode);let pick=buttons[0];if(g.mode==='upgrade'){const rank=b=>{const n=priorities.findIndex(p=>b.textContent.toUpperCase().startsWith(p.toUpperCase()));return n<0?99:n;};pick=buttons.sort((a,b)=>rank(a)-rank(b))[0];}if(g.mode==='trial')pick=buttons.find(b=>b.textContent.startsWith('SANCTUARY'))||pick;pick.click();decisions++;continue;}
 // A constant-turn movement bot, steering around walls. Same policy/seeds before and after.
 const desired=g.clock*.24;g.joy.dx=g.joy.dy=0;for(const offset of [0,.4,-.4,.8,-.8,1.2,-1.2,1.6,-1.6,2,-2,Math.PI]){const a=desired+offset,dx=Math.cos(a),dy=Math.sin(a);if(!g.wallAt(g.hero.x+dx*30,g.hero.y+dy*30,g.hero.r)){g.joy.dx=dx;g.joy.dy=dy;break;}}
 g.update(.025);maxImps=Math.max(maxImps,g.enemies.filter(e=>e.type==='cinderImp'&&e.hp>0).length);maxLava=Math.max(maxLava,g.zoneHazards.filter(z=>z.kind==='lava').length);
}
g.draw();return {version,kind,seed,seconds:+g.clock.toFixed(2),alive:!['over','error'].includes(g.mode)&&g.hero.hp>0,hp:+g.hero.hp.toFixed(1),kills:g.kills,level:g.level,mode:g.mode,floor:g.dungeon.floor,exitReason:g.dungeon.floor>1?'clearedFloor':g.hero.hp<=0?'death':g.clock>=180?'timeCap':'stepCap',maxImps,maxLava,decisions,initial};},{kind,seed,version});results.push(result);console.log(JSON.stringify(result));
}
await page.evaluate(()=>{gameTest.enemies=[];gameTest.begin();});await page.evaluate(()=>gameTest.draw());await page.screenshot({path:`/tmp/descent-tuning-${version}.png`});await page.evaluate(()=>localStorage.clear());}
await page.goto(`http://localhost:${server.address().port}/`);
const checks=await page.evaluate(()=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}g.applyProfile({bosses:3});g.selectedHero='bloodknight';g.selectedMode='descent';g.begin();g.enemies=[];
function enemy(x,y){const e={x,y,r:10,type:'ghoul',hp:1000,max:1000,speed:0,attack:99};g.enemies.push(e);return e;}
g.hero.x=1000;g.hero.y=800;g.hero.moving=1;g.hero.faceX=1;g.hero.faceY=0;const behind=enemy(940,800);g.swingBlade();check(behind.hp<1000&&g.hero.faceX<0,'Moving aim misses behind');g.enemies=[];g.hero.faceX=1;g.hero.faceY=0;const far=enemy(850,800);g.swingBlade();check(far.hp===1000&&g.hero.faceX===1,'Out-of-reach fallback');g.enemies=[];g.hero.x=220;g.hero.y=600;g.hero.faceY=1;g.hero.faceX=0;const blocked=enemy(220,535),clear=enemy(220,680);g.swingBlade();check(blocked.hp===1000&&clear.hp<1000,'Aim through wall');
g.enemies=[];g.hero.x=400;g.hero.y=800;for(let i=0;i<6;i++)g.spawnEnemy('cinderImp');check(g.enemies.filter(e=>e.type==='cinderImp').length===3,'Cinder cap');g.floorEntry(2);for(let i=0;i<6;i++)g.spawnEnemy('cinderImp');check(g.enemies.filter(e=>e.type==='cinderImp').length===6,'Cap leaked to later floor');g.draw();const map=document.querySelector('#dungeonMap'),r=map.getBoundingClientRect();check(r.width<105&&r.height<70&&+getComputedStyle(map).opacity<1,'Minimap dimensions/opacity');return true;});assert(checks);assert.equal(errors.length,0,errors.join('\n'));
const summary={};for(const kind of ['gravecaller','ranger','ember','bloodknight','sunwarden']){summary[kind]={};for(const version of ['before','after']){const oldKind={gravecaller:'mage',ranger:'storm'}[kind]||kind;const runs=results.filter(r=>r.kind===(version==='before'?oldKind:kind)&&r.version===version);if(!runs.length){summary[kind][version]=null;continue;}const times=runs.map(r=>r.seconds).sort((a,b)=>a-b);summary[kind][version]={medianSeconds:times[2],rangeSeconds:[times[0],times[4]],survived180:runs.filter(r=>r.alive&&r.seconds>=180).length,clearedFloor:runs.filter(r=>r.floor>1).length,maxImps:Math.max(...runs.map(r=>r.maxImps)),maxLava:Math.max(...runs.map(r=>r.maxLava))};}}
const report={baselineCommit,policy:'Five seeded constant-turn joystick bots per hero/version, wall avoidance and offered upgrades, depth 0, no shrine purchases or HP/damage overrides. 180-second Floor 1 cap. Automated normal-stat survival diagnostic, not a human playtest.',seeds:[17,37,71,113,151],summary,results,browserErrors:errors};fs.writeFileSync(path.resolve(root,process.env.RESULT_PATH||'tests/descent-tuning-results.json'),JSON.stringify(report,null,2)+'\n');console.log('SUMMARY',JSON.stringify(summary));console.log('PASS: syntax, normal-stat runs, moving aim/reach/LOS, Cinder cap and smaller translucent minimap');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
