// Chromium checks for authored topology and doorway arrival announcements.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..'),source=require('./classic-camera-fixture.cjs')(fs.readFileSync(path.join(root,'index.html'),'utf8').replace('function music(kind) {','function music(kind) { return;'));
for(const m of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1]);
const hooks=`window.gameTest={begin,floorEntry,floorSpec,dungeonSolid,spawnEnemy,update,draw,damageEnemy,afflict,saveRun,readRun,restoreRun,arrivalGroups,clearWall,
get hero(){return hero},get dungeon(){return dungeon},get enemies(){return enemies},set enemies(v){enemies=v},get shots(){return shots},get clock(){return clock},get mode(){return mode},set mode(v){mode=v},set spawn(v){spawn=v},get slots(){return slots},set selectedMode(v){selectedMode=v}};`;
const html=source.replace('function sfx(kind) {','function sfx(kind) { return;').replace('function music(kind) {','function music(kind) { return;').replaceAll('requestAnimationFrame(frame);','').replace('      })();',hooks+'\n      })();');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}const file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://localhost:${server.address().port}`);await page.getByRole('button',{name:'TAP TO START'}).click({force:true});await page.getByRole('button',{name:'SLOT 1 · + NEW CHARACTER',exact:true}).click();await page.locator('input').fill('Explorer');await page.getByRole('button',{name:'CREATE & PLAY',exact:true}).click();
 const maps=await page.evaluate(()=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}const layouts=[],results=[];
 function reachable(blocked=new Set()){const start=Math.floor(g.hero.x/80)+','+Math.floor(g.hero.y/80),seen=new Set([start]),queue=[start];for(let i=0;i<queue.length;i++){const [x,y]=queue[i].split(',').map(Number);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const key=(x+dx)+','+(y+dy);if(!blocked.has(key)&&!g.dungeonSolid(x+dx,y+dy)&&!seen.has(key)){seen.add(key);queue.push(key);}}}return seen;}
 for(let floor=1;floor<=5;floor++){g.floorEntry(floor);const spec=g.floorSpec();layouts.push(JSON.stringify([spec.rooms,spec.links]));let visited=reachable();for(let i=0;i<spec.rooms.length;i++){const [x,y,w,h]=spec.rooms[i],center=Math.floor(x+w/2)+','+Math.floor(y+h/2);check(visited.has(center)===(i!==3),'Closed-door room connectivity floor '+floor+' room '+i);}g.dungeon.open=true;visited=reachable();check(visited.size===g.dungeon.cells.size,'Disconnected floor '+floor);for(const entrance of g.dungeon.entrances){check(!g.dungeonSolid(Math.floor(entrance.x/80),Math.floor(entrance.y/80)),'Doorway in wall');check(entrance.x<25*80,'Ordinary doorway inside boss chamber');}
 if(floor===1)check(spec.rooms[4][2]*spec.rooms[4][3]<=24&&spec.rooms[1][3]<=6,'Ash lacks introductory chambers');if(floor===2)check(spec.rooms[1][3]>=10&&spec.rooms[2][3]>=10,'Frost lacks long halls');if(floor===3)check(spec.rooms[1][2]*spec.rooms[1][3]>=50,'Venom lacks central hub');if(floor===4){const blocked=new Set();for(const x of [8,9,16,17])for(const y of [9,10])blocked.add(x+','+y);const alternative=reachable(blocked);for(const i of [1,2]){const [x,y,w,h]=spec.rooms[i];check(alternative.has(Math.floor(x+w/2)+','+Math.floor(y+h/2)),'Sunken loop missing');}}if(floor===5)check(spec.links.some(r=>r[0]===20&&r[2]>=5),'Heart lacks approach');results.push({floor,name:spec.name,cells:g.dungeon.cells.size,entrances:g.dungeon.entrances.length});}
 check(new Set(layouts).size===5,'Repeated layout');return results;});
 // Capture each floor's actual viewport/minimap, with explored rooms exposed only in this test.
 for(let floor=1;floor<=5;floor++){await page.evaluate(n=>{gameTest.floorEntry(n);gameTest.dungeon.explored=[0,1,2,3,4,5,6];gameTest.dungeon.title=0;gameTest.draw();},floor);await page.screenshot({path:`/tmp/descent-variety-floor-${floor}.png`});}
 await page.evaluate(()=>{const g=gameTest;g.selectedMode='descent';g.begin();g.spawn=999;g.dungeon.title=0;const e=g.spawnEnemy('ghoul');if(!e||e.arrivingUntil!==g.clock+1)throw Error('Missing arrival warning');g.hero.x=e.x+Math.cos(e.entryAngle)*200;g.hero.y=e.y+Math.sin(e.entryAngle)*200;g.clearWall(g.hero);e.hp=e.max=2000;window.arrivalFixture={e,x:e.x,y:e.y,hp:e.hp,heroHp:g.hero.hp};g.draw();});await page.screenshot({path:'/tmp/descent-doorway-warning.png'});
 const warnings=await page.evaluate(()=>{const g=gameTest,{e,x,y,hp,heroHp}=arrivalFixture;function check(v,m){if(!v)throw Error(m);}g.damageEnemy(e,1);check(e.hp===hp-1,'Emerging shadow cannot be interrupted');check(g.arrivalGroups().length===1,'Missing portal group');g.mode='pause';g.update(.5);check(g.clock===0&&g.arrivalGroups()[0].remaining===1,'Paused warning timer advances');g.mode='play';for(let i=0;i<20;i++)g.update(.025);check((e.x!==x||e.y!==y)&&g.hero.hp===heroHp&&g.arrivalGroups().length===1,'Arrival announcement does not precede safe approach');check(e.hp<hp-1,'Automatic attacks ignore emerging shadow');for(let i=0;i<22;i++)g.update(.025);check(g.clock>e.arrivingUntil&&(e.x!==x||e.y!==y),'Enemy did not approach');check(!g.arrivalGroups().length,'Expired warning stays active');g.saveRun(true);check(g.readRun().version===12,'Save version changed');g.restoreRun();check(!g.enemies.length&&g.dungeon.floor===1&&g.dungeon.entrances.length>0,'Checkpoint carries pending arrivals');g.selectedMode='endless';g.begin();const arena=g.spawnEnemy('ghoul');check(!arena.arrivingUntil&&!arena.entryId,'Endless spawn changed');return true;});assert(warnings);
 await page.evaluate(()=>{const g=gameTest;g.selectedMode='descent';g.begin();g.spawn=999;g.dungeon.title=0;const e=g.spawnEnemy('ghoul');g.hero.x=e.x+Math.cos(e.entryAngle)*200;g.hero.y=e.y+Math.sin(e.entryAngle)*200;g.clearWall(g.hero);for(let i=0;i<20;i++)g.update(.025);g.draw();});await page.screenshot({path:'/tmp/descent-doorway-warning-mid.png'});
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: five distinct connected layouts, locked chambers, Sunken bypass loops, doorway announcement/normal approach/interruptible arrivals, paused timers, v11 floor restart and unchanged Endless spawns');console.log(JSON.stringify(maps));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
