// Phone layouts, two-thumb input, dash/slams, hero ultimates, additive saves and normal charge timing.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const source=require('./classic-camera-fixture.cjs')(fs.readFileSync(path.join(root,'index.html'),'utf8').replace('function music(kind) {','function music(kind) { return;'));for(const m of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1]);
const hooks=`window.gameTest={begin,applyProfile,saveProfile,selectSlot,saveRun,readRun,restoreRun,makeSaveCode,loadSaveCode,renderMenu,renderHeroScreen,update,draw,updateHud,wallAt,floorEntry,spawnBoss,damageEnemy,takeHit,raiseMinion,useDash,useUltimate,updateSkills,dashCooldown,updateSkillButtons,pauseRun,resumePaused,
get hero(){return hero},get profile(){return profile},get joy(){return joy},get keys(){return keys},get enemies(){return enemies},set enemies(v){enemies=v},get companions(){return companions},get shots(){return shots},set shots(v){shots=v},get meteors(){return meteors},get clock(){return clock},set clock(v){clock=v},get mode(){return mode},set mode(v){mode=v},get dungeon(){return dungeon},get kills(){return kills},get level(){return level},get slots(){return slots},get floorCheckpoint(){return floorCheckpoint},get flash(){return flash},set selectedHero(v){selectedHero=v},set selectedMode(v){selectedMode=v},set spawn(v){spawn=v}};`;
function instrument(live=false){let s=source;if(!live)s=s.replaceAll('requestAnimationFrame(frame);','').replace('function sfx(kind) {','function sfx(kind) { return;');return s.replace('      })();',hooks+'\n      })();');}
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/'||name==='/live'){res.setHeader('Content-Type','text/html');return res.end(instrument(name==='/live'));}const file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.end(fs.readFileSync(file));});
const heroes=['gravecaller','ranger','ember','bloodknight','sunwarden'],sizes=[{width:390,height:844},{width:844,height:390}],errors=[],report={orientations:[],combat:[],charge:[],saves:null,browserErrors:errors};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const url=`http://localhost:${server.address().port}`;
try{const page=await browser.newPage({viewport:sizes[0],hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Skills',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');});await page.goto(url);await page.evaluate(()=>gameTest.selectSlot(0));
for(const size of sizes){await page.setViewportSize(size);for(const kind of heroes){const result=await page.evaluate(({kind,size})=>{const g=gameTest;g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();g.dungeon.title=0;g.update(.025);g.draw();const r=id=>{let b=document.querySelector(id).getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};},inside=b=>b.x>=0&&b.y>=0&&b.right<=size.width+1&&b.bottom<=size.height+1,overlap=(a,b)=>a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y;const dash=r('#dashButton'),ult=r('#ultimateButton'),hud=r('.hud'),map=r('#dungeonMap'),pause=r('#pauseControl'),canvas=r('#view');function check(v,m){if(!v)throw Error(kind+': '+m);}check(canvas.width===size.width&&canvas.height===size.height,'Canvas not full viewport');check(inside(dash)&&inside(ult)&&inside(map),'Offscreen controls');check(!overlap(dash,ult)&&!overlap(dash,hud)&&!overlap(ult,hud),'Skill overlap');check(!overlap(map,hud)&&!overlap(map,pause),'Minimap overlap');check(map.x>size.width/2,'Minimap not top-right');if(size.width>size.height){check(dash.width===(size.height<450?56:72)&&ult.width===dash.width,'Landscape thumb targets');check(getComputedStyle(document.querySelector('#joystick')).visibility==='hidden','Floating joystick visible while idle');}else check(!overlap(dash,r('#joystick'))&&!overlap(ult,r('#joystick')),'Portrait joystick overlap');return {kind,...size,dash,ultimate:ult,hud,minimap:map};},{kind,size});report.orientations.push(result);
 await page.evaluate(()=>{gameTest.hero.ultimateCharge=100;gameTest.updateHud();});await page.screenshot({path:`/tmp/skills-${kind}-${size.width}.png`});
 }console.log('PASS: all five heroes, full canvas/HUD/right minimap/skill geometry',size);
 // Menus including hero selection and Settings remain scrollable to their last control.
 for(const screen of ['hub','modes','heroes','shrine','settings','bestiary','achievements','slots']){await page.evaluate(screen=>gameTest.renderMenu(screen),screen);const last=page.locator('#menuPage button').last();await last.scrollIntoViewIfNeeded();assert(await last.isVisible());const b=await last.boundingBox();assert(b.y>=0&&b.y+b.height<=size.height+1,`${screen} clipped at ${size.width}`);}console.log('PASS: menus',size);
}
if(process.env.LAYOUT_ONLY){console.log('PASS: layout-only verification');return;}
// Real multi-touch events: moving left thumb remains captured while right thumb presses skills.
await page.setViewportSize(sizes[1]);await page.evaluate(()=>{const g=gameTest;g.selectedHero='gravecaller';g.begin();g.hero.ultimateCharge=100;g.updateHud();});const cdp=await page.context().newCDPSession(page);
const dispatch=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints});
await dispatch('touchStart',[{x:180,y:260,id:1}]);await dispatch('touchMove',[{x:220,y:260,id:1}]);assert(await page.evaluate(()=>gameTest.joy.dx>.7&&document.querySelector('#joystick').classList.contains('active')));
let dash=await page.locator('#dashButton').boundingBox();await dispatch('touchStart',[{x:220,y:260,id:1},{x:dash.x+36,y:dash.y+36,id:2}]);assert(await page.evaluate(()=>gameTest.hero.dashTime===.25&&gameTest.joy.dx>.7));await dispatch('touchEnd',[]);await dispatch('touchStart',[{x:180,y:260,id:1}]);await dispatch('touchMove',[{x:220,y:260,id:1}]);let ult=await page.locator('#ultimateButton').boundingBox();await dispatch('touchStart',[{x:220,y:260,id:1},{x:ult.x+36,y:ult.y+36,id:3}]);assert(await page.evaluate(()=>gameTest.hero.ultimateCharge===0&&gameTest.companions.filter(p=>p.ultimateMinion).length===8&&gameTest.joy.dx>.7));await dispatch('touchEnd',[]);assert(await page.evaluate(()=>gameTest.joy.id===null&&gameTest.joy.dx===0));
await dispatch('touchStart',[{x:500,y:260,id:4}]);assert(await page.evaluate(()=>gameTest.joy.id===null));await dispatch('touchEnd',[]);
await dispatch('touchStart',[{x:120,y:260,id:5}]);await page.setViewportSize(sizes[0]);await page.waitForFunction(()=>gameTest.joy.id===null&&!document.querySelector('#joystick').classList.contains('active'));await dispatch('touchEnd',[]);console.log('PASS: simultaneous left joystick + Dash + Ultimate, right exclusion, release and rotation reset');
// Desktop shortcuts invoke exactly one skill, and never trigger in menus/inputs.
await page.evaluate(()=>{const g=gameTest;g.begin();g.hero.inv=0;g.hero.ultimateCharge=100;});await page.keyboard.down('d');await page.keyboard.press('Space');assert(await page.evaluate(()=>gameTest.hero.dashX>0&&gameTest.hero.dashCd===4));await page.keyboard.up('d');await page.keyboard.press('e');assert(await page.evaluate(()=>gameTest.hero.ultimateCharge===0));await page.evaluate(()=>{gameTest.renderMenu('settings');gameTest.hero.ultimateCharge=100;gameTest.hero.dashCd=0;});await page.locator('textarea[placeholder="Paste save code"]').fill('e space');assert(await page.evaluate(()=>gameTest.hero.ultimateCharge===100&&gameTest.hero.dashCd===0));console.log('PASS: WASD/Space/E and menu typing');
report.combat=await page.evaluate(heroes=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}function reset(kind){g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();g.enemies=[];g.spawn=999;g.hero.inv=0;g.dungeon.title=0;g.hero.x=400;g.hero.y=800;}
function foe(x,y,hp=1000,type='ghoul'){const e={x,y,hp,max:hp,type,r:12,speed:0,attack:99,cast:99,faceX:0,faceY:1};g.enemies.push(e);return e;}const result=[];
for(const kind of heroes){reset(kind);g.hero.faceX=1;g.hero.faceY=0;g.spawnBoss('colossus');const b=g.enemies.find(e=>e.type==='boss');b.x=480;b.y=800;b.speed=0;b.pulse=999;b.slamClock=999;b.slam={x:g.hero.x,y:g.hero.y,r:1000,damage:37,time:.05,duration:1.3};const before={hp:g.hero.hp,armor:g.hero.armor};check(g.useDash(),'Dash refused');check(g.hero.dashX===1&&g.hero.dashY===0,'Stationary facing direction');check(!g.useDash(),'Repeat Dash allowed');g.update(.025);g.update(.025);check(!b.slam&&g.hero.hp===before.hp&&g.hero.armor===before.armor,'Dash failed actual boss slam '+kind);check(g.takeHit(20)===0,'Dash direct damage bypass');for(let i=0;i<9;i++)g.update(.025);check(g.hero.dashTime===0,'Dash lasts >0.25s');g.hero.inv=0;b.slam={x:g.hero.x,y:g.hero.y,r:1000,damage:37,time:.01,duration:1.3};const armor=g.hero.armor;g.update(.025);check(g.hero.armor<armor||g.hero.hp<before.hp,'Post-Dash slam never damages');g.enemies=[];for(let i=0;i<150;i++)g.update(.025);check(g.hero.dashCd===0,'4s cooldown not elapsed');
 reset(kind);g.hero.x=220;g.hero.y=600;g.hero.faceX=0;g.hero.faceY=-1;check(g.useDash(),'Wall Dash refused');for(let i=0;i<10;i++)g.update(.025);check(g.hero.y>=574&&!g.wallAt(g.hero.x,g.hero.y,g.hero.r),'Dash tunnels dungeon wall '+kind);
 reset(kind);g.hero.ultimateCharge=99;check(!g.useUltimate(),'Uncharged ult allowed');g.hero.ultimateCharge=100;g.hero.hp=40;const target=foe(470,800),blocked=foe(220,535);check(g.useUltimate(),'Ult refused '+kind);check(g.hero.ultimateCharge===0&&g.flash>0,'Ult charge/flash');check(!g.useUltimate(),'Repeated ult');
 if(kind==='ember'){check(g.hero.firestormTime===5,'Firestorm duration');g.updateSkills(.025);check(g.meteors.length>0&&g.meteors.every(m=>m.ultimate&&m.time>0),'Firestorm meteors');for(let i=0;i<201;i++)g.updateSkills(.025);check(g.hero.firestormTime===0,'Firestorm expiry');const count=g.meteors.length;g.updateSkills(1);check(g.meteors.length===count,'Firestorm never ends');}
 if(kind==='bloodknight'){check(target.hp<1000&&target.stunUntil>g.clock&&blocked.hp===1000,'Earthsplitter damage/stun/walls');check(g.hero.ultimateCharge===0,'Ultimate self charge');}
 if(kind==='gravecaller'){check(g.companions.filter(p=>p.ultimateMinion).length===8&&g.companions.every(p=>p.life===15),'Army size/lifetime');for(let i=0;i<4;i++)g.raiseMinion(420,800);check(g.companions.length===12,'Army consumes normal capacity');}
 if(kind==='ranger'){check(g.shots.length===32&&g.shots.every(p=>p.ultimate&&p.chain&&p.arrow),'Arrow Storm volley');check(g.shots.some(p=>p.vx>500)&&g.shots.some(p=>p.vx<-500)&&g.shots.some(p=>p.vy>500)&&g.shots.some(p=>p.vy<-500),'Not 360 degrees');const hp=target.hp;for(let i=0;i<8;i++)g.update(.025);check(target.hp<hp,'Ultimate arrows do not hit');}
 if(kind==='sunwarden'){check(g.hero.hp===g.hero.maxHp&&target.solarBlindUntil===g.clock+4&&!blocked.solarBlindUntil,'Solar heal/blind/on-screen/walls');}
 result.push({hero:kind,dashSlams:'blocked during dash, damages after',dashWalls:'passed',ultimate:'passed'});
}
reset('gravecaller');const dense=foe(440,800,1000000);for(let i=0;i<100;i++)g.damageEnemy(dense,g.hero.damage);check(g.hero.ultimateCharge<=8,'Burst recharges Ultimate instantly');g.enemies=[];const charge=g.hero.ultimateCharge;g.update(1);check(g.hero.ultimateCharge===charge,'Idle passive charge');g.hero.ultimateCharge=100;g.useUltimate();const sustained=foe(440,800,1000000);for(let i=0;i<40*59;i++){g.clock+=.025;g.updateSkills(.025);g.damageEnemy(sustained,g.hero.damage*3);}check(g.hero.ultimateCharge<100,'Ultimate refills in under 60 seconds');for(let i=0;i<50;i++){g.clock+=.025;g.updateSkills(.025);g.damageEnemy(sustained,g.hero.damage*3);}check(g.hero.ultimateCharge===100,'Continuous combat never refills Ultimate '+JSON.stringify({charge:g.hero.ultimateCharge,clock:g.clock,mode:g.mode,hp:g.hero.hp}));g.enemies=[];g.profile.upgrades.fleetStep=4;check(g.dashCooldown()===2.8,'Fleet Step');g.useDash();check(g.hero.dashCd===2.8,'Fleet Step cooldown applied');g.mode='paused';const cd=g.hero.dashCd;g.update(1);check(g.hero.dashCd===cd&&g.hero.dashTime===.25,'Paused skill timers');return result;},heroes);console.log('PASS: all hero Ultimates, actual boss slams/invulnerability expiry, wall-swept Dash, Fleet Step, paused cooldowns');
report.saves=await page.evaluate(()=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}g.mode='play';g.applyProfile({ranger:true,upgrades:{fleet:2,fleetStep:3},embers:123,total:777,achievements:{boss3:true}});g.selectedHero='ranger';g.selectedMode='endless';g.begin();g.hero.dashCd=2.5;g.hero.ultimateCharge=63;g.saveRun(true);g.saveProfile();g.restoreRun();check(g.hero.dashCd===2.5&&g.hero.ultimateCharge===63&&g.profile.upgrades.fleetStep===3,'Endless skills save');const code=g.makeSaveCode(),decoded=g.loadSaveCode(code);check(decoded.run.hero.ultimateCharge===63&&decoded.profile.embers===123,'EC1 skill roundtrip');
 const legacy=g.readRun();for(const k of ['dashCd','dashTime','ultimateCharge','firestormTime','firestormCd','ultimateUsedAt','ultimateWindow','ultimateWindowEarned'])delete legacy.hero[k];localStorage.setItem('ember-crypt-slot-1-run-v11',JSON.stringify(legacy));g.restoreRun();check(g.hero.dashCd===0&&g.hero.ultimateCharge===0&&g.hero.dashTime===0,'Old v11 fields defaults');check(g.profile.upgrades.fleet===2&&g.profile.achievements.boss3,'Progress lost');
 g.selectedHero='gravecaller';g.selectedMode='endless';g.begin();g.hero.ultimateCharge=100;g.useUltimate();g.saveRun(true);g.restoreRun();check(g.companions.filter(p=>p.ultimateMinion).length===8,'Army save lost');
 g.selectedMode='descent';g.begin();g.floorEntry(3);g.hero.ultimateCharge=71;g.saveRun(true);g.restoreRun();check(g.dungeon.floor===3&&g.dungeon.elapsed===0&&Number.isFinite(g.hero.ultimateCharge),'Floor checkpoint skills restore');const before=localStorage.getItem('ember-crypt-slot-1-profile');const slots=JSON.parse(localStorage.getItem('ember-crypt-character-slots-v1'));slots[1]={name:'Other',lastPlayed:1,playTime:0};localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify(slots));g.slots[1]=slots[1];g.selectSlot(1);check(g.profile.embers===0&&!g.profile.upgrades.fleetStep,'Skills leak to slot2');check(localStorage.getItem('ember-crypt-slot-1-profile')===before,'Slot1 modified');return 'v11 missing-field defaults, profile upgrades/progress, Endless cooldown/charge/Army, Descent checkpoint, EC1 codes and slot isolation';});console.log('PASS:',report.saves);
// Reuse the established normal-stat constant-turn policy. Track charge readiness, do not use skills or boost stats.
for(const size of sizes){await page.setViewportSize(size);for(const kind of heroes){const result=await page.evaluate(({kind,size})=>{const g=gameTest;let state=37;Math.random=()=>{state=(state+0x6D2B79F5)|0;let t=Math.imul(state^(state>>>15),1|state);t=(t+Math.imul(t^(t>>>7),61|t))^t;return ((t^(t>>>14))>>>0)/4294967296;};g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();let ready=null,decisions=0;const initial={hp:g.hero.hp,damage:g.hero.damage,armor:g.hero.armor,depth:g.hero.depth,shrine:{...g.profile.upgrades}};const priorities=kind==='bloodknight'?['EVOLUTION','Crimson Thirst','Bloodletting','Stone Skin','Blood Fairy','Shockwave','Earth Spikes','Berserk','Twin Flame','Long Reach','Quake Step','Earth Fairy','Quick Hands','Iron Heart']:['EVOLUTION','Twin Flame','Quick Hands','Bone Armor','Raise Legion','Siphon','Spirit Wisps','Ice Trap','Glacier Wolf','Frost Arrows','Chain Shot','Radiance','Sanctuary','Gale','Cyclone','ARCANE LANCE','Chain Spark','METEOR SIGIL','GRAVE NOVA','Firebrand','Venom Bolts','Fairy','Iron Heart'];
for(let step=0;step<40*180+200;step++){if(['over','error','victory'].includes(g.mode)||g.clock>=180||g.dungeon.floor!==1)break;if(g.mode!=='play'){let buttons=[...document.querySelectorAll('#choices .choice')].filter(b=>!b.disabled);if(!buttons.length)throw Error('Missing choice '+g.mode);let pick=buttons[0];if(g.mode==='upgrade'){const rank=b=>{let i=priorities.findIndex(p=>b.textContent.toUpperCase().startsWith(p.toUpperCase()));return i<0?99:i;};pick=buttons.sort((a,b)=>rank(a)-rank(b))[0];}if(g.mode==='trial')pick=buttons.find(b=>b.textContent.startsWith('SANCTUARY'))||pick;pick.click();decisions++;continue;}const desired=g.clock*.24;g.joy.dx=g.joy.dy=0;for(const offset of [0,.4,-.4,.8,-.8,1.2,-1.2,1.6,-1.6,2,-2,Math.PI]){const a=desired+offset,dx=Math.cos(a),dy=Math.sin(a);if(!g.wallAt(g.hero.x+dx*30,g.hero.y+dy*30,g.hero.r)){g.joy.dx=dx;g.joy.dy=dy;break;}}g.update(.025);if(ready===null&&g.hero.ultimateCharge>=100)ready=+g.clock.toFixed(2);}
g.draw();return {hero:kind,...size,seed:37,readySeconds:ready,seconds:+g.clock.toFixed(2),kills:g.kills,level:g.level,charge:+g.hero.ultimateCharge.toFixed(2),mode:g.mode,decisions,initial};},{kind,size});assert(result.readySeconds!==null?result.readySeconds>=60&&result.readySeconds<=90:result.mode==='over'&&result.seconds<90,`${kind} charge timing ${size.width}: ${result.readySeconds} (${result.mode} at ${result.seconds}s)`);report.charge.push(result);console.log('CHARGE',JSON.stringify(result));}}
// Native frame loop + real controls, all ten hero/orientation combinations.
for(const size of sizes)for(const kind of heroes){const live=await browser.newPage({viewport:size,hasTouch:true});live.on('pageerror',e=>errors.push(e.message));await live.addInitScript(kind=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Live Skills',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');localStorage.setItem('ember-crypt-slot-1-profile',JSON.stringify({version:2,selectedHero:kind,ranger:true,ember:true,bloodknight:true,sunwarden:true,migrated:true,upgrades:{},embers:0,total:0}));},kind);await live.goto(url+'/live');await live.getByRole('button',{name:'TAP TO START'}).click({force:true});await live.getByRole('button',{name:'PLAY',exact:true}).click();await live.getByRole('button',{name:/^THE DESCENT/}).click();await live.getByRole('button',{name:/^ENTER THE CRYPT/}).click();await live.keyboard.down('ArrowRight');await live.locator('#dashButton').tap();await live.waitForTimeout(350);await live.keyboard.up('ArrowRight');assert(await live.evaluate(()=>gameTest.hero.dashCd>0&&gameTest.hero.dashTime===0));await live.evaluate(()=>{gameTest.hero.ultimateCharge=100;gameTest.updateHud();});await live.locator('#ultimateButton').tap();await live.waitForTimeout(450);assert(await live.evaluate(()=>gameTest.hero.ultimateCharge<100&&gameTest.mode==='play'));await live.screenshot({path:`/tmp/skills-live-${kind}-${size.width}.png`});await live.close();}
console.log('PASS: native 40 FPS frame loop with real Dash/Ultimate button input, all ten hero/orientation combinations');assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(root,'tests/landscape-skills-results.json'),JSON.stringify(report,null,2)+'\n');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
