// New lineup mechanics and genuine v10 -> v11/profile-v2 migration in Chromium.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const source=require('./classic-camera-fixture.cjs')(fs.readFileSync(path.join(root,'index.html'),'utf8')),baselineCommit='990662055e59f37a70c831bae6458d8c8db04ec0';
for(const m of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1]);
const legacy=execFileSync('git',['show',baselineCommit+':index.html'],{cwd:root,encoding:'utf8'});
const common=`begin,clearRun,codeChecksum,applyProfile,saveProfile,selectSlot,saveRun,readRun,restoreRun,offerLoot,makeSaveCode,loadSaveCode,floorEntry,damageEnemy,levelUp,renderMenu,renderHeroScreen,update,draw,wallAt,segmentBlocked,evolutionReady,
get hero(){return hero},get profile(){return profile},get enemies(){return enemies},set enemies(v){enemies=v},get shots(){return shots},set shots(v){shots=v},get clock(){return clock},set clock(v){clock=v},get mode(){return mode},set mode(v){mode=v},set spawn(v){spawn=v},get level(){return level},set level(v){level=v},get dungeon(){return dungeon},get joy(){return joy},get slots(){return slots},set selectedHero(v){selectedHero=v},get selectedHero(){return selectedHero},set selectedMode(v){selectedMode=v}`;
const extra=`raiseMinion,skeletonCap,nearbyAlly,updateCompanions,updatePrototypeHeroes,updateSunwarden,updateTraps,fireRanger,prototypeCards,prototypeEvolutions,beamEnds,matchup,sunHit,
get companions(){return companions},set companions(v){companions=v},get traps(){return heroTraps},set traps(v){heroTraps=v},get spirits(){return heroSpirits},get zones(){return heroZones},get art(){return art}`;
function instrument(s,old=false){return s.replace('function sfx(kind) {','function sfx(kind) { return;').replace('function music(kind) {','function music(kind) { return;').replaceAll('requestAnimationFrame(frame);','').replace('      })();',`window.gameTest={${common}${old?'':','+extra}};\n      })();`);}
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);if(name==='/'||name==='/legacy'||name==='/live'){res.setHeader('Content-Type','text/html');return res.end(name==='/legacy'?instrument(legacy,true):name==='/live'?source:instrument(source));}const file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=`http://localhost:${server.address().port}`;await page.goto(url);await page.getByRole('button',{name:'TAP TO START'}).click({force:true});await page.getByRole('button',{name:'SLOT 1 · + NEW CHARACTER',exact:true}).click();await page.locator('input').fill('Prototype');await page.getByRole('button',{name:'CREATE & PLAY',exact:true}).click();await page.waitForFunction(()=>gameTest.art['ranger-cast']&&gameTest.art['sunwarden-cast']&&gameTest.art.wolf&&gameTest.art.skeleton);
 const mechanics=await page.evaluate(()=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}function reset(kind){g.applyProfile({bosses:3,ranger:true,ember:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();g.spawn=999;g.enemies=[];g.hero.x=400;g.hero.y=800;}function foe(x=440,y=800,hp=1000,type='ghoul'){const e={x,y,hp,max:hp,type,r:12,speed:0,attack:99,faceX:0,faceY:1};g.enemies.push(e);return e;}
 check(g.hero.class==='gravecaller'&&g.profile.version===2,'New starter/profile version');g.applyProfile({});g.selectedHero='sunwarden';g.renderHeroScreen();check(document.querySelector('#menuPage').textContent.includes('Reach floor 3 in The Descent'),'Sunwarden locked condition');g.selectedHero='gravecaller';g.begin();g.floorEntry(2);check(!g.profile.sunwarden,'Early Sunwarden unlock');g.floorEntry(3);check(g.profile.sunwarden&&g.profile.bestFloor===3,'Floor-three unlock');
 reset('gravecaller');const random=Math.random;Math.random=()=>.34;g.damageEnemy(foe(440,800,1),10,'shadow');check(g.companions.length===1&&g.companions[0].life===25,'35% raise/lifetime');Math.random=()=>.36;g.damageEnemy(foe(440,800,1),10,'arcane');check(g.companions.length===1,'Raise probability threshold');Math.random=random;for(let i=0;i<10;i++)g.raiseMinion(440,800);check(g.companions.length===4,'Default skeleton cap');g.hero.evolutions=['legion'];check(g.skeletonCap()===8,'Legion cap multiplier');
 let target=foe(455,800);check(g.nearbyAlly(target),'Enemies ignore nearby allies');const bossTarget=foe(455,800,1000,'boss');check(!g.nearbyAlly(bossTarget),'Boss distracted by summons');g.enemies.splice(g.enemies.indexOf(bossTarget),1);const minion=g.companions[0];minion.cd=0;g.hero.soulLink=1;g.hero.siphon=1;g.hero.hp=80;g.updateCompanions(.025);check(target.hp<1000&&g.hero.hp>80,'Minion melee/link/siphon');const hp=minion.hp;for(let i=0;i<50;i++)g.updateCompanions(.025);check(minion.hp<hp,'Enemies cannot hurt minions');
 reset('gravecaller');g.hero.graveBurst=2;g.hero.evolutions=['soulstorm'];g.raiseMinion(430,800);target=foe(450,800);g.companions[0].life=.01;g.updateCompanions(.025);check(!g.companions.length&&target.hp<1000&&g.spirits.length===3,'Expiry burst/homing spirits');const before=target.hp;for(let i=0;i<20;i++)g.updatePrototypeHeroes(.025);check(target.hp<before,'Homing spirits never hit');
 reset('gravecaller');g.hero.minionCapacity=5;g.hero.evolutions=['ossuary'];for(let i=0;i<5;i++)g.raiseMinion(430,800);g.updateCompanions(.025);check(g.companions.length===1&&g.companions[0].kind==='giant'&&g.companions[0].life>14,'Ossuary merge');g.companions[0].life=.01;g.updateCompanions(.025);check(!g.companions.length,'Giant expiry');
 reset('gravecaller');g.hero.x=220;g.hero.y=600;g.companions=[];g.raiseMinion(220,600);target=foe(220,535);g.companions[0].cd=0;g.updateCompanions(.025);check(target.hp===1000,'Minions hit through walls');g.hero.spiritWisps=2;g.draw();
 reset('ranger');target=foe(460,800);g.fireRanger();check(g.shots.length===1&&g.shots[0].arrow&&!g.shots[0].chain&&!g.shots[0].splash&&g.shots[0].pierceLeft===0,'Arrow is not single target');const wolf=g.companions[0];wolf.x=440;wolf.y=800;wolf.cd=0;g.hero.glacierWolf=1;g.updateCompanions(.025);check(target.hp<1000&&target.frostTime>0,'Wolf bite/chill');g.hero.evolutions=['alpha'];g.updateCompanions(.025);check(g.companions.filter(p=>p.kind==='wolf').length===2&&g.companions[1].max===102,'Alpha second wolf/card HP on new ally');g.shots=[];g.hero.thunderVolley=true;g.hero.shotCount=5;g.fireRanger();check(g.shots.length===5,'Sixth shot volley');
 reset('ranger');g.hero.moving=1;g.hero.trapCd=0;g.updateTraps(.025);check(g.traps.length===1,'Moving auto trap');g.hero.moving=0;g.hero.trapCd=0;g.updateTraps(.025);check(g.traps.length===1,'Standing produces traps');target=foe(410,800);g.hero.iceTrap=1;g.hero.shockTrap=1;g.updateTraps(.025);check(!g.traps.length&&target.hp<1000&&target.stunUntil>g.clock,'Trap freeze/lightning');
 g.hero.evolutions=['blizzard'];g.traps=[{x:350,y:800,r:10,life:12},{x:500,y:800,r:10,life:12}];target=foe(420,815);g.updateTraps(.025);check(target.hp<1000&&target.stunUntil>g.clock,'Linked freezing wall');
 reset('sunwarden');check(!g.companions.length,'Sunwarden has unintended companions');target=foe(500,800);g.hero.beamAngle=0;g.hero.beamTick=0;g.hero.hp=60;g.updateSunwarden(.025);check(target.hp<1000&&g.hero.hp>60,'Light beam/regen');const oldX=target.x;g.hero.gustCd=0;g.updateSunwarden(.025);check(target.x>oldX,'Gust knockback');g.hero.sanctuary=1;g.hero.stillTime=1.3;g.hero.sanctuaryCd=0;g.updateSunwarden(.025);check(g.zones.some(z=>z.kind==='sanctuary'),'Stationary sanctuary');g.hero.evolutions=['halo','dawn'];g.hero.x+=30;g.updateSunwarden(.025);check(g.zones.find(z=>z.kind==='sanctuary').x===g.hero.x&&g.beamEnds().length===3,'Halo/Dawnbreaker');
 reset('sunwarden');g.hero.x=220;g.hero.y=600;g.hero.beamAngle=-Math.PI/2;g.hero.beamTick=0;target=foe(220,535);g.updateSunwarden(.025);check(target.hp===1000&&g.beamEnds()[0].length<80,'Light beam through wall');g.hero.cyclone=1;g.hero.cycloneCd=0;g.updateSunwarden(.025);check(g.zones.some(z=>z.kind==='cyclone'),'Cyclone missing');
 reset('sunwarden');target=foe(500,800,1000,'skeleton');g.damageEnemy(target,20,'light');check(target.hp===970,'Light weakness');target=foe(500,800,1000,'caster');g.damageEnemy(target,20,'light');check(target.hp===990,'Light resist');target=foe(500,800,1000,'runner');g.damageEnemy(target,20,'wind');check(target.hp===970,'Wind weakness');target=foe(500,800,1000,'brute');g.damageEnemy(target,20,'wind');check(target.hp===990,'Wind resist');for(const kind of ['skeleton','wraith','heart'])check([].concat(g.matchup(kind==='heart'?{type:'boss',variant:'heart'}:{type:kind}).weak).includes('light'),'Missing light weakness '+kind);for(const kind of ['runner','cinderImp','sporeSpitter'])check([].concat(g.matchup({type:kind}).weak).includes('wind'),'Missing wind weakness '+kind);for(const kind of ['caster','oracle'])check([].concat(g.matchup(kind==='oracle'?{type:'boss',variant:'oracle'}:{type:kind}).resist).includes('light'),'Missing light resist '+kind);for(const kind of ['brute','sentinel','frostGolem'])check([].concat(g.matchup({type:kind}).resist).includes('wind'),'Missing wind resist '+kind);
 reset('sunwarden');g.hero.critChance=1;g.hero.critMultiplier=2;target=foe(500,800);g.sunHit(target,10,'light');check(target.hp===980,'Shared crit stats do not apply to beam');
 const paths=[['gravecaller','legion',{minionCapacity:6,boneArmor:2}],['gravecaller','ossuary',{minionCapacity:5,soulLink:2}],['gravecaller','soulstorm',{graveBurst:2,fairies:['shadow']}],['ranger','shatter',{frostBolts:true,chain:3}],['ranger','alpha',{glacierWolf:2,chain:2}],['ranger','blizzard',{iceTrap:2,fairies:['frost']}],['sunwarden','dawn',{radiance:2,fairies:['light']}],['sunwarden','eye',{gale:2,cyclone:2}],['sunwarden','halo',{sanctuary:2,fairies:['wind']}]];
 for(const [kind,key,fields]of paths){reset(kind);check(!g.evolutionReady(key),'Evolution starts unlocked '+key);Object.assign(g.hero,fields);check(g.evolutionReady(key),'Evolution prerequisites '+key);g.level=8;g.levelUp();check(document.querySelector('#choices .evolution'),'No gold evolution offered '+key);}
 reset('sunwarden');target=foe(500,880);g.hero.beamAngle=0;g.hero.beamTick=0;g.updateSunwarden(.001);check(target.hp===1000,'Base beam width');g.hero.radiance=2;g.hero.beamAngle=0;g.hero.beamTick=0;g.updateSunwarden(.001);check(target.hp<1000&&target.dazzledUntil>g.clock,'Radiance width/dazzle');target=foe(500,800,1000,'boss');target.variant='warden';g.hero.judgment=1;g.hero.judgmentCd=0;g.updateSunwarden(.001);check(target.hp<1000&&g.zones.some(z=>z.kind==='pillar'),'Judgment elite pillar');
 reset('sunwarden');g.offerLoot({wave:3});check(!document.querySelector('#choices').textContent.includes('undefined'),'Sunwarden gear effect missing');document.querySelector('#choices .choice').click();check(['light','wind'].includes(g.hero.weaponEffect),'Sunwarden weapon elements');
 reset('ranger');g.offerLoot({wave:3});check(/bow/i.test(document.querySelector('#choices').textContent)&&!document.querySelector('#choices').textContent.includes('undefined'),'Ranger gear identity');
 reset('ranger');foe(470,800);g.hero.projectiles=2;foe(450,860);g.fireRanger();check(g.shots.length===2&&Math.abs(g.shots[0].vy-g.shots[1].vy)>100,'Twin arrows lack independent targets');g.enemies=[];foe(350,800);g.hero.moving=1;g.hero.faceX=1;g.hero.faceY=0;g.fireRanger();check(g.hero.aimX<0&&g.hero.faceX===1,'Bow aim alters movement facing');g.draw();
 const allowed={gravecaller:['arcane','shadow','shared'],ranger:['frost','lightning','shared'],sunwarden:['light','wind','shared'],ember:['fire','poison','shared'],bloodknight:['blood','earth','shared']},cards={};
 for(const kind of Object.keys(allowed)){reset(kind);cards[kind]=new Set();for(let i=0;i<90;i++){g.level=5;g.levelUp();for(const b of document.querySelectorAll('#choices .choice')){const element=b.className.split(' ').find(v=>['arcane','shadow','frost','lightning','light','wind','fire','poison','blood','earth','shared'].includes(v));if(element)check(allowed[kind].includes(element),'Wrong card element '+kind+' '+element);cards[kind].add(b.querySelector('span')?.textContent);}}cards[kind]=[...cards[kind]];}
 check(cards.gravecaller.includes('Bone Armor')&&cards.ranger.includes('Thunder Volley')&&cards.sunwarden.includes('Sanctuary'),'Missing new cards');
 reset('ranger');const life=g.companions[0].life;g.mode='paused';g.update(1);check(g.companions[0].life===life,'Paused companions update');g.mode='play';g.selectedMode='endless';g.begin();g.hero.moving=1;g.hero.trapCd=0;g.updateTraps(.025);g.saveRun(true);const saved=g.readRun();check(saved.version===12&&saved.companions.length===1&&saved.heroTraps.length===1,'v11 actor serialization');g.restoreRun();check(g.companions.length===1&&g.traps.length===1,'Endless actors lost');g.updateCompanions(.025);check(g.companions.length===1,'Saved wolf immediately expired');
 return {cards,checks:'starter, unlock, summoning odds/caps/lifetimes, damage/link/siphon, mortal allies, Grave Burst/Legion/Ossuary/Soul Storm, walls, arrows/wolf/traps/volley/Alpha/Blizzard, beam/gust/regen/Sanctuary/Halo/Dawnbreaker/Cyclone, matchups, element cards, pause and actor saves'};});console.log('PASS:',mechanics.checks);
 // Produce authentic old profiles/runs using the actual preceding implementation.
 await page.goto(url+'/legacy');const old=await page.evaluate(()=>{const g=gameTest,slots=g.slots;slots[1]={name:'Old Ranger',lastPlayed:1,playTime:321};slots[2]={name:'Old Knight',lastPlayed:2,playTime:456};localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify(slots));const results=[];
 for(const [slot,kind]of [[0,'mage'],[1,'storm'],[2,'bloodknight']]){g.selectSlot(slot);g.applyProfile({selectedHero:kind,embers:123+slot,total:777,storm:true,ember:true,bloodknight:true,bosses:7,achievements:{boss3:true,wave10:true},upgrades:{power:2,vigor:1},unlockedDepth:4,bestDepth:{mage:3,storm:2,bloodknight:1},records:{descent:{kills:234,bestDepth:{mage:2,storm:1}},endless:{kills:345,bestDepth:{mage:3,storm:2}}},tips:{move:true}});g.selectedHero=kind;g.saveProfile();g.selectedMode=slot===1?'endless':'descent';g.begin();if(slot===0)g.floorEntry(3);g.hero.hp=7;g.saveRun(true);results.push({slot,kind,code:g.makeSaveCode(),run:g.readRun(),profile:JSON.parse(localStorage.getItem('ember-crypt-slot-'+(slot+1)+'-profile'))});localStorage.removeItem('ember-crypt-slot-'+(slot+1)+'-run-v12');}return results;});
 await page.goto(url);const migration=await page.evaluate(old=>{const g=gameTest;function check(v,m){if(!v)throw Error(m);}const mappings={mage:'gravecaller',storm:'ranger',bloodknight:'bloodknight'};for(const item of old){g.selectSlot(item.slot);const profile=g.profile,saved=g.readRun();check(profile.version===2&&profile.embers===123+item.slot&&profile.total===777&&profile.upgrades.power===2&&profile.achievements.boss3&&profile.tips.move,'Progress lost slot '+item.slot);check(profile.ranger&&profile.bestDepth.gravecaller===3&&profile.bestDepth.ranger===2&&profile.records.descent.bestDepth.gravecaller===2&&profile.records.endless.bestDepth.ranger===2,'Hero records/unlock lost');check(g.selectedHero===mappings[item.kind]&&saved.version===12&&saved.hero.class===mappings[item.kind],'Hero replacement failed');check(!localStorage.getItem('ember-crypt-slot-'+(item.slot+1)+'-run-v10'),'Old key not migrated');g.restoreRun();check(g.hero.class===mappings[item.kind],'Wrong resumed hero');if(item.slot===0)check(g.dungeon.floor===3&&g.dungeon.elapsed===0&&g.hero.hp>7&&profile.sunwarden,'Removed starter/floor checkpoint resume');if(item.slot===1)check(!g.dungeon&&g.hero.hp===g.hero.maxHp&&g.enemies.length===0&&g.companions.length===1,'Removed ranger safe arena restart');check(g.slots[1].name==='Old Ranger'&&g.slots[2].name==='Old Knight','Slot metadata lost');const decoded=g.loadSaveCode(item.code);check(decoded.profile.version===2&&decoded.run.version===12&&decoded.run.hero.class===mappings[item.kind],'Old save code migration');const code=g.makeSaveCode();check(g.loadSaveCode(code).run.version===12,'v11 code roundtrip');}
 g.selectSlot(0);const v9=structuredClone(old[0].run);v9.version=9;v9.balanceVersion=9;delete v9.runMode;delete v9.floor;delete v9.floorCheckpoint;localStorage.removeItem('ember-crypt-slot-1-run-v12');localStorage.setItem('ember-crypt-slot-1-run-v9',JSON.stringify(v9));g.restoreRun();check(!g.dungeon&&g.hero.class==='gravecaller'&&g.readRun().version===12,'v9 -> Endless replacement');return true;},old);assert(migration);console.log('PASS: genuine old Mage/Ranger/Bloodknight runs, v9/v10→v11, profile v2, embers/shrine/achievements/tips/records/unlocks, slot isolation, legacy/v11 save codes');
 for(const kind of ['gravecaller','ranger','sunwarden']){await page.evaluate(kind=>{const g=gameTest;g.applyProfile({ranger:true,sunwarden:true});g.selectedHero=kind;g.selectedMode='descent';g.begin();g.dungeon.title=0;if(kind==='gravecaller')for(let i=0;i<3;i++)g.raiseMinion(410+i*30,840);if(kind==='ranger'){g.hero.moving=1;g.hero.trapCd=0;g.updateTraps(.025);}if(kind==='sunwarden'){g.hero.sanctuary=1;g.hero.stillTime=1.3;g.updateSunwarden(.025);}g.draw();},kind);await page.screenshot({path:`/tmp/new-heroes-${kind}.png`});}
 // All five heroes also run on the untouched requestAnimationFrame loop at normal stats.
 for(const kind of ['gravecaller','ranger','ember','bloodknight','sunwarden']){const live=await browser.newPage({viewport:{width:390,height:844}});live.on('pageerror',e=>errors.push(e.message));await live.addInitScript(kind=>{localStorage.setItem('ember-crypt-character-slots-v1',JSON.stringify([{name:'Live Hero',lastPlayed:1,playTime:60},null,null]));localStorage.setItem('ember-crypt-active-slot-v1','0');localStorage.setItem('ember-crypt-slot-1-profile',JSON.stringify({version:2,selectedHero:kind,ranger:true,ember:true,bloodknight:true,sunwarden:true,bosses:3,migrated:true,upgrades:{},embers:0,total:0}));},kind);await live.goto(url+'/live');await live.getByRole('button',{name:'TAP TO START'}).click({force:true});await live.getByRole('button',{name:'PLAY',exact:true}).click();await live.getByRole('button',{name:/^THE DESCENT/}).click();await live.getByRole('button',{name:/^ENTER THE CRYPT/}).click();await live.keyboard.down('ArrowRight');await live.waitForTimeout(1200);await live.keyboard.up('ArrowRight');await live.waitForTimeout(1200);assert(await live.locator('#game').evaluate(e=>e.classList.contains('playing')));await live.screenshot({path:`/tmp/new-heroes-live-${kind}.png`});await live.close();}
 console.log('PASS: unmodified live frame loop, normal stats, joystick movement and mobile canvas for all five heroes');
 const playtestCode=await page.evaluate(()=>{const g=gameTest;g.applyProfile({ranger:true,ember:true,bloodknight:true,sunwarden:true,bestFloor:3,bosses:3,achievements:{boss3:true},migrated:true,embers:0,total:0,upgrades:{}});g.selectedHero='gravecaller';g.mode='menu';g.clearRun();const payload=g.loadSaveCode(g.makeSaveCode());payload.name='Hero Preview';payload.best=0;payload.playTime=0;const json=JSON.stringify(payload);let binary='';for(const byte of new TextEncoder().encode(json))binary+=String.fromCharCode(byte);return 'EC1.'+g.codeChecksum(json)+'.'+btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');});fs.writeFileSync(path.join(root,'tests/new-heroes-playtest.ec1.txt'),playtestCode+'\n');
 // New atlas PNG fallback is exercised independently of WebP success.
 const fallback=await browser.newPage({viewport:{width:390,height:844}});fallback.on('pageerror',e=>errors.push(e.message));await fallback.route('**/assets/cinematic/new-heroes.webp',route=>route.abort());await fallback.goto(url);await fallback.waitForFunction(()=>gameTest.art['ranger-cast']&&gameTest.art['sunwarden-cast']&&gameTest.art['wolf-cast']);assert(await fallback.evaluate(()=>gameTest.art.ranger.naturalWidth>0&&gameTest.art.sunwarden.naturalWidth>0));await fallback.close();
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: three new hero renders, transparent WebP sheet, new atlas PNG fallback, no browser errors');
 fs.writeFileSync('/tmp/new-heroes-tests.json',JSON.stringify({mechanics,migration,baselineCommit,browserErrors:errors},null,2)+'\n');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
